#!/bin/bash
#SBATCH --job-name=orcajob
#SBATCH --account=project_2017403
#SBATCH --partition=small
#SBATCH --time=12:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH --cpus-per-task=8
#SBATCH --output=orca_env_test_%j.out
#SBATCH --error=orca_env_test_%j.err

module purge
module load StdEnv
module use /projappl/project_2017403/modules
module load orca-env/1.0

/projappl/project_2017403/orca/orca6/orca test.inp > test.out
